//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.30 at 10:29:31 AM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.batepapo.com/xml/users", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.com.batepapo.batepapouserssoapwebservices.dto;
